### ISSUE TITLE
Pixel size and simulated OTF for fairSIM

### ISSUE THREAD

**Issue by Trave11er** [fairSIM/fairSIM-documentation#2]
Hello! When trying to model superresolution capabilities of a microscope with fairSIM I have come across two issues and would be grateful if you could clarify those:

1) The ImageJ plugin only allows pixel sizes up to 500 nm - is it possible to use larger ones?

2) My OTF simulated with MATLAB is a matrix - can it be converted into a format required by fairSIM?

Thank you, Gleb

**Comment by mueller-physics** [comment]
Hello Gleb,

1. We have limited pixel sizes to those that reasonably might be used in fluorescence microscopy, this is 
why the plugin will only accept them between 20nm and 500nm. These limits are, however, only enforced by the GUI, the algorithmic parts of the code won't check them.
If you are comfortable with compiling the code yourself, you can simply change them / comment them out in [line 207](https://github.com/fairSIM/fairSIM/blob/master/org/fairsim/sim_gui/ImageControl.java#L207) and [line 263](https://github.com/fairSIM/fairSIM/blob/master/org/fairsim/sim_gui/ImageControl.java#L263) of the "ImageControl.java" file.
Physically, of course, your pixel size always has to be at most half of your expected wide-field resolution, otherwise you'll have problems undersampling the data.

2. fairSIM uses a radially averaged OTF, where the OTF strength only depends on the spatial frequency, not any component of orientation. If your MATLAB OTF computation is of that format, the easiest way would possibly be to convert it into fairSIMs internal format (we have a converter [here](https://github.com/fairSIM/SRSIM-misc-tools) that does something similar).
If you require a full 2D OTF, the easiest way would probably be to convert it into something like a TIFF, and read it in as image data. However, this would require some modifications to the code (so you'd need some Java experience, probably). 
A good place to start and to look at the code in this case is a scripted version of a full SIM reconstruction, which can be found [here](https://github.com/fairSIM/fairSIM/blob/develop/org/fairsim/fiji/TestPlugin.java).

Also, since you seem to be running your simulations (at least partially) in Matlab, are you aware of the following to projects?

* [SIM Toolbox](http://mmtg.fel.cvut.cz/simtoolbox/)
* [OpenSIM](https://github.com/LanMai/OpenSIM)

Both are Matlab-based, open-source approaches to SIM reconstruction. They both have a somewhat different focus then fairSIM (which mainly aims to provide a ready-to-use solution to ImageJ / FIJI users), but might be more suited to your needs if you aim to interface with lots of Matlab code.

I hope this helps you. Feel free to contact me or open a new issue if further questions should arise.

Marcel

P.S.: This issue was opened for "fairSIM documentation", though it was probably aimed for the main project. I am going to close it here.

**Comment by Trave11er** [comment]
Hello Marcel,

Thank you for taking time to write such an extensive reply - that is really helpful and greatly appreciated. Knowing the exact lines for the pixel restrictions in 1. is really helpful. Regarding, 2. Will try to use the converter provided.

As for the other two projects mentioned - have come across those but as you noted fairSIM is very easy to use so will try to stick with it.

Many thanks again and have a great day,
Gleb
